version: 0.2

phases:
  build:
    commands:
      - echo "Preparing frontend files for deployment..."
      - cd frontend
      - ls -la
      
  post_build:
    commands:
      - echo "Deploying to S3 bucket cc-photo-bucket-b1-v-cf..."
      - aws s3 sync . s3://cc-photo-bucket-b1-v-cf/ --delete --exclude ".git/*" --exclude "buildspec.yml" --exclude "*.md"
      - echo "Frontend deployed successfully to cc-photo-bucket-b1-v-cf!"

artifacts:
  files:
    - '**/*'
  base-directory: frontend
