version: 0.2

phases:
  install:
    commands:
      - echo "No build dependencies required for static frontend"
      
  build:
    commands:
      - echo "Preparing frontend files for deployment..."
      - ls -la
      
  post_build:
    commands:
      - echo "Deploying to S3 bucket cc-photo-bucket-b1..."
      - aws s3 sync . s3://cc-photo-bucket-b1/ --exclude "buildspec.yml" --exclude ".git/*" --delete
      - echo "Frontend deployment completed successfully!"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - buildspec.yml
    - .git/**/*
